version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: eventhub-db
    environment:
      POSTGRES_USER: academy_user
      POSTGRES_PASSWORD: academy_password
      POSTGRES_DB: eventhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventhub-network

  adminer:
    image: adminer:latest
    container_name: eventhub-adminer
    ports:
      - "8090:8080"
    depends_on:
      - postgres-db
    networks:
      - eventhub-network
volumes:
  postgres_data:

networks:
  eventhub-network:
    driver: bridge