# Configurazione Database (PostgreSQL in Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub_db
spring.datasource.username=academy_user
spring.datasource.password=academy_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
#dire a Spring Boot di eseguire il file data.sql
spring.sql.init.mode=always 