INSERT INTO role (name) VALUES ('ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_ORGANIZER') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;