INSERT INTO role (id, name) VALUES (1, 'ROLE_USER') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, name) VALUES (2, 'ROLE_ORGANIZER') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, name) VALUES (3, 'ROLE_ADMIN') ON CONFLICT (id) DO NOTHING;